export const queryKeys = {
  getConversations: "getConversations",
  sendMessage: "sendMessage",
  getMessages: "getMessages",
  openingPositions: "openingPositions",
  position: "position",
  historicalPositions: "historicalPositions",
  balances: "balances",
  positionHistory: "positionHistory",
  userMe: "userMe",
  pools: "pools",
  nativePrice: "nativePrice",
  overview: "overview",
  decreaseQuotes: "decreaseQuotes",
  pricePin: "pricePin",
} as const;
